jobs:

  - job: build_all_window
    pool:
      vmImage: 'windows-2019'
    variables:
      phpVersion: 7.2
    steps: 

    - powershell: ./scripts/aelf-node/deploy-node.ps1
    - powershell: Start-Process powershell.exe -ArgumentList 'dotnet c:\aelf\aelf-node\AElf.Launcher.dll'
    - task: CmdLine@2
      inputs:
        script: |
          sleep 600
          netstat -an
          sleep 100
          netstat -an
